/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <donator>

public Plugin:myinfo = 
{
	name = "Donator Menu Hook Sample",
	author = "Nut",
	description = "",
	version = "0.1",
	url = ""
}

public OnPluginStart()
{
	
}

public OnAllPluginsLoaded()
{
	if(!LibraryExists("donator.core")) SetFailState("Unabled to find plugin: Donator Interface");

	Donator_RegisterMenuItem("Donator Command Example", CommandCallback);
	Donator_RegisterMenuItem("Donator Sub Menu Example", SubMenuCallback);
}

public DonatorMenu:CommandCallback(iClient) CommandOne(iClient);
public DonatorMenu:SubMenuCallback(iClient) SubMenuOne(iClient);

public CommandOne(iClient)
{
	//do whatever here - client selected it from the menu
	PrintToChat(iClient, "You selected command one");
}

public SubMenuOne(iClient)
{
	new Handle:hMenu = CreateMenu(SubMenuExample);
	SetMenuTitle(hMenu,"Donator: Set Birthday:");

	
	AddMenuItem(hMenu, "item1", "First menu item", ITEMDRAW_DEFAULT);
	AddMenuItem(hMenu, "item2", "Second menu item", ITEMDRAW_DISABLED);
	AddMenuItem(hMenu, "item3", "Third menu item", ITEMDRAW_DEFAULT);
	
	DisplayMenu(hMenu, iClient, 20);
}

public SubMenuExample(Handle:menu, MenuAction:action, param1, param2)
{
	decl String:tmp[32];
	GetMenuItem(menu, param2, tmp, sizeof(tmp));

	switch (action)
	{
		case MenuAction_Select: PrintToChat(param1, "You picked item %s", tmp);
		case MenuAction_End: CloseHandle(menu);
	}
}
